# ================== HF_AssWall ==================== #

# [[Scenes]] # HF_AssWall
# Id = "HF_AssWall"

# [[Scenes.Performers]]
# Performer = "HF_AssWall_Man_FemaleNative"
# StartConditions = []
# PerformConditions = []

# [[Scenes.Performers]]
# Performer = "HF_AssWall_Man_NativeGirl"
# StartConditions = []
# PerformConditions = []

# [[Scenes.Performers]]
# Performer = "HF_AssWall_Man_FemaleLargeNative"
# StartConditions = []
# PerformConditions = []

# [[Scenes.Performers]]
# Performer = "HF_AssWall_Man_UnderGroundWoman"
# StartConditions = []
# PerformConditions = []

# [[Scenes.Performers]]
# Performer = "HF_AssWall_Man_ElderSisterNative"
# StartConditions = []
# PerformConditions = []



# ================== HF_CommonSexPlayer ==================== #

[[Scenes]] # HF_CommonSexPlayer
Id = "HF_CommonSexPlayer"

# -------------------------------------

# Man x Reika is complex...
# - Main_Reika1 == 3 means they are lovers (initial condition)
# - Sub_Keigo   == 2 means you have defeated Keigo but not killed him.
#                  Unlocks special scene on SexType = 1
# - Sub_Keigo   in 0, 4, 5 means you either didn't face Keigo or killed him
#                  Only has base scene.
# - Sub_Keigo   == 1 means you gave up on Reika, so can't sex her anymore
[[Scenes.Performers]]
Performer = "HF_Man_Reika_Friendly_Cowgirl"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Main_Reika1", "==", 3] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]

[[Scenes.Performers]]
Performer = "HF_Man_Reika_Friendly_RevCowgirl"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Main_Reika1", "==", 3] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]

[[Scenes.Performers]]
Performer = "HF_Man_Reika_Friendly_RevCowgirl"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Main_Reika1", "==", 3] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "in", [0, 4, 5]] },
]
PerformConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "!=", 2] },
]

# ---------------------------------

[[Scenes.Performers]] # HF_Man_FemaleNative_Friendly_Normal
Performer = "HF_Man_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_FemaleNative_Friendly_Pregnant
Performer = "HF_Man_FemaleNative_Friendly_Pregnant"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_NativeGirl_Friendly_Normal
Performer = "HF_Man_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_FemaleLargeNative_Friendly_Cowgirl_Normal
Performer = "HF_Man_FemaleLargeNative_Friendly_Cowgirl_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleLargeNative#17", false] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # HF_Man_FemaleLargeNative_Friendly_Doggy_Normal
Performer = "HF_Man_FemaleLargeNative_Friendly_Doggy_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleLargeNative#17", false] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

[[Scenes.Performers]] # HF_Man_Mummy_Friendly_Normal
Performer = "HF_Man_Mummy_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["Mummy#42", false] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_UnderGroundWoman_Friendly_Normal
Performer = "HF_Man_UnderGroundWoman_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["UnderGroundWoman#44", false] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_Mermaid_Friendly_TittyFuck
Performer = "HF_Man_Mermaid_Friendly_TittyFuck"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["Mermaid#71", false] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # HF_Man_Mermaid_Friendly_Fuck
Performer = "HF_Man_Mermaid_Friendly_Fuck"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["Mermaid#71", false] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

[[Scenes.Performers]] # HF_Man_ElderSisterNative_Friendly_Doggy_Normal
Performer = "HF_Man_ElderSisterNative_Friendly_Doggy_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["ElderSisterNative#90", false] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_Giant_Friendly_Normal
Performer = "HF_Man_Giant_Friendly_Normal"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Giant", "==", 4] },
]
PerformConditions = []

[[Scenes.Performers]] # HF_Man_Cassie2_Friendly_Normal
Performer = "HF_Man_Cassie2_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # HF_Man_Shino_Friendly_TittyFuck
Performer = "HF_Man_Shino_Friendly_TittyFuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # HF_Man_Shino_Friendly_Fuck
Performer = "HF_Man_Shino_Friendly_Fuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

# -------- Man x Sally -------- #
# It is a special case, as there are 2 paths for it to happen.

[[Scenes.Performers]] # HF_Man_Sally_Friendly_Normal
Performer = "HF_Man_Sally_Friendly_Normal"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Prison", "in", [2, 4]] },
]
PerformConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Prison", "in", [2, 4]] },
]

[[Scenes.Performers]] # HF_Man_Sally_Friendly_Normal
Performer = "HF_Man_Sally_Friendly_Normal"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Prison", "==", 3] },
	{ Type = "LibidoCheck", Args = ["Sally#115", ">", 80.0] },
]
PerformConditions = [
	{ Type = "QuestProgressCheck", Args = ["Sub_Prison", "==", 3] },
	{ Type = "LibidoCheck", Args = ["Sally#115", ">", 80.0] },
]

# ----------------------------- #

[[Scenes.Performers]] # HF_Man_Merry_Friendly_Normal
Performer = "HF_Man_Merry_Friendly_Normal"
StartConditions = []
PerformConditions = []

### ======= Yona

[[Scenes.Performers]] # HF_Yona_MaleNative_Friendly_Normal
Performer = "HF_Yona_MaleNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # HF_Yona_BigNative_Friendly_Normal
Performer = "HF_Yona_BigNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # HF_Yona_SmallNative_Friendly_Normal
Performer = "HF_Yona_SmallNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # HF_Yona_ElderBrotherNative_Friendly_Normal
Performer = "HF_Yona_ElderBrotherNative_Friendly_Normal"
StartConditions = []
PerformConditions = []



# ================== HF_CommonSexNPC ==================== #

[[Scenes]] # HF_CommonSexNPC
Id = "HF_CommonSexNPC"

[[Scenes.Performers]]
Performer = "HF_MaleNative_FemaleNative_Friendly_Doggy_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_FemaleNative_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_FemaleNative_Friendly_Pregnant"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_MaleNative_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_NativeGirl_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_FemaleLargeNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleLargeNative#17", false] },
]
PerformConditions = []

# SexCheck suggests this is possible, but CommonSexNPC does not support it
# [[Scenes.Performers]]
# Performer = "HF_YoungMan_Mummy_Friendly_Normal"
# StartConditions = [
# 	{ Type = "PregnantCheck", Args = ["Mummy#42", false] },
# ]
# PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_UnderGroundWoman_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["UnderGroundWoman#44", false] },
]
PerformConditions = []

# SexCheck suggests this is possible, but CommonSexNPC does not support it
# [[Scenes.Performers]]
# Performer = "HF_YoungMan_Mermaid_Friendly_Normal"
# StartConditions = [
# 	{ Type = "PregnantCheck", Args = ["Mermaid#71", false] },
# ]
# PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_YoungMan_ElderSisterNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["ElderSisterNative#90", false] },
]
PerformConditions = []


# ================== HF_ManRapes ==================== #

[[Scenes]] # HF_ManRapes
Id = "HF_ManRapes"

[[Scenes.Performers]]
Performer = "HF_Man_Yona_Rape"
StartConditions = [
	{ Type = "FaintCheck", Args = ["Yona#0", true] },
]
PerformConditions = [
	{ Type = "FaintCheck", Args = ["Yona#0", true] },
]

[[Scenes.Performers]]
Performer = "HF_Man_FemaleNative_Rape_Fainted"
StartConditions = [
	{ Type = "FaintCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = [
	{ Type = "FaintCheck", Args = ["FemaleNative#15", true] },
]

[[Scenes.Performers]]
Performer = "HF_Man_FemaleNative_Rape_Grapple"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]

[[Scenes.Performers]]
Performer = "HF_Man_FemaleNative_Rape_Grapple_Pregnant"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]

[[Scenes.Performers]]
Performer = "HF_Man_NativeGirl_Rape_Fainted"
StartConditions = [
	{ Type = "FaintCheck", Args = ["NativeGirl#16", true] },
]
PerformConditions = [
	{ Type = "FaintCheck", Args = ["NativeGirl#16", true] },
]

[[Scenes.Performers]]
Performer = "HF_Man_NativeGirl_Rape_Grapple"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]

[[Scenes.Performers]]
Performer = "HF_Man_FemaleLargeNative_Rape"
StartConditions = [
	{ Type = "FaintCheck", Args = ["FemaleLargeNative#17", true] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Man_FemaleLargeNative_Rape"
StartConditions = [
	{ Type = "FriendCheck", Args = ["FemaleLargeNative#17", true] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Man_OldWomanNative_Rape"
StartConditions = [
	{ Type = "JokeCheck", Args = [true] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Man_Mummy_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Man_ElderSisterNative_Rape"
StartConditions = []
PerformConditions = []

# ================== HF_ManRapesSleep ==================== #

[[Scenes]] # HF_ManRapesSleep
Id = "HF_ManRapesSleep"

[[Scenes.Performers]]
Performer = "HF_Man_FemaleNative_SleepRape_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Man_NativeGirl_SleepRape_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []



# ================== HF_PlayerRaped ==================== #

[[Scenes]] # HF_PlayerRaped
Id = "HF_PlayerRaped"

[[Scenes.Performers]]
Performer = "HF_MaleNative_Yona_Rape_Doggy_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_BigNative_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Bigfoot_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Werewolf_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Oldguy_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Spike_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Planton_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_BossNative_Yona_Rape"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_FemaleLargeNative_Man_Rape_Battle"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_FemaleLargeNative_Man_Rape_Sex"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Mummy_Man_Rape_Battle_Sex"
StartConditions = []
PerformConditions = []



# ================== HF_Toilet ==================== #

[[Scenes]] # HF_Toilet
Id = "HF_Toilet"

[[Scenes.Performers]]
Performer = "HF_MaleNative_Yona_Rape_Doggy_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Toilet_Man_FemaleNative"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Toilet_Man_NativeGirl"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Toilet_Man_FemaleLargeNative"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Toilet_Man_UnderGroundWoman"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "HF_Toilet_Man_ElderSisterNative"
StartConditions = []
PerformConditions = []
