# ================== EHS_CommonSexPlayer ==================== #

[[Scenes]] # EHS_CommonSexPlayer
Id = "EHS_CommonSexPlayer"

[[Scenes.Performers]]
Performer = "EHS_Man_Reika_Friendly_Cowgirl"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Main_Reika1", "==", 3] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "==", 2] },
]

[[Scenes.Performers]]
Performer = "EHS_Man_Reika_Friendly_RevCowgirl"
StartConditions = [
	{ Type = "QuestProgressCheck", Args = ["Main_Reika1", "==", 3] },
	{ Type = "QuestProgressCheck", Args = ["Sub_Keigo", "in", [0, 4, 5]] },
]
PerformConditions = [
	# { Type = "QuestProgressCheck", Args = ["Sub_Keigo", "!=", 2] }, # Original code check, but we are covered
]

[[Scenes.Performers]] # EHS_Man_FemaleNative_Friendly_Normal
Performer = "EHS_Man_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_FemaleNative_Friendly_Pregnant
Performer = "EHS_Man_FemaleNative_Friendly_Pregnant"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_NativeGirl_Friendly_Normal
Performer = "EHS_Man_NativeGirl_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_FemaleLargeNative_Friendly_Cowgirl_Normal
Performer = "EHS_Man_FemaleLargeNative_Friendly_Cowgirl_Normal"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # EHS_Man_FemaleLargeNative_Friendly_Doggy_Normal
Performer = "EHS_Man_FemaleLargeNative_Friendly_Doggy_Normal"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

[[Scenes.Performers]] # EHS_Man_Mummy_Friendly_Normal
Performer = "EHS_Man_Mummy_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_UnderGroundWoman_Friendly_Normal
Performer = "EHS_Man_UnderGroundWoman_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_Mermaid_Friendly_TittyFuck
Performer = "EHS_Man_Mermaid_Friendly_TittyFuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # EHS_Man_Mermaid_Friendly_Fuck
Performer = "EHS_Man_Mermaid_Friendly_Fuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

[[Scenes.Performers]] # EHS_Man_ElderSisterNative_Friendly_Doggy_Normal
Performer = "EHS_Man_ElderSisterNative_Friendly_Doggy_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_Giant_Friendly_Normal
Performer = "EHS_Man_Giant_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_Cassie2_Friendly_Normal
Performer = "EHS_Man_Cassie2_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_Shino_Friendly_TittyFuck
Performer = "EHS_Man_Shino_Friendly_TittyFuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [0] },
]

[[Scenes.Performers]] # EHS_Man_Shino_Friendly_Fuck
Performer = "EHS_Man_Shino_Friendly_Fuck"
StartConditions = []
PerformConditions = [
	{ Type = "SexTypeCheck", Args = [1] },
]

[[Scenes.Performers]] # EHS_Man_Sally_Friendly_Normal
Performer = "EHS_Man_Sally_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Man_Merry_Friendly_Normal
Performer = "EHS_Man_Merry_Friendly_Normal"
StartConditions = []
PerformConditions = []

### ======= Yona

[[Scenes.Performers]] # EHS_Yona_MaleNative_Friendly_Normal
Performer = "EHS_Yona_MaleNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Yona_BigNative_Friendly_Normal
Performer = "EHS_Yona_BigNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Yona_SmallNative_Friendly_Normal
Performer = "EHS_Yona_SmallNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]] # EHS_Yona_ElderBrotherNative_Friendly_Normal
Performer = "EHS_Yona_ElderBrotherNative_Friendly_Normal"
StartConditions = []
PerformConditions = []



# ================== EHS_CommonSexNPC ==================== #

[[Scenes]] # EHS_CommonSexNPC
Id = "EHS_CommonSexNPC"

[[Scenes.Performers]]
Performer = "EHS_MaleNative_FemaleNative_Friendly_Doggy_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_FemaleNative_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_FemaleNative_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_FemaleNative_Friendly_Pregnant"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["FemaleNative#15", true] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_MaleNative_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_NativeGirl_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_NativeGirl_Friendly_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_FemaleLargeNative_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_UnderGroundWoman_Friendly_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_YoungMan_ElderSisterNative_Friendly_Normal"
StartConditions = []
PerformConditions = []



# ================== EHS_ManRapesSleep ==================== #

[[Scenes]] # EHS_ManRapesSleep
Id = "EHS_ManRapesSleep"

[[Scenes.Performers]]
Performer = "EHS_Man_FemaleNative_SleepRape_Normal"
StartConditions = []
PerformConditions = []

[[Scenes.Performers]]
Performer = "EHS_Man_NativeGirl_SleepRape_Normal"
StartConditions = [
	{ Type = "PregnantCheck", Args = ["NativeGirl#16", false] },
]
PerformConditions = []



# ================== EHS_PlayerRaped ==================== #

[[Scenes]] # EHS_PlayerRaped
Id = "EHS_PlayerRaped"

[[Scenes.Performers]]
Performer = "EHS_MaleNative_Yona_Rape_Doggy_Normal"
StartConditions = []
PerformConditions = []
