/* Auto-generated by HFramework. This must stay in an Editor folder */
#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using HFramework.EditorUI;
using HFramework.SexScripts;
using HFramework.ScriptNodes;

namespace HFrameworkTemplates /* You can customize if you want */
{
	public partial class HFrameworkTemplates_Menus
	{
		[MenuItem("Assets/Create/HFramework/HF_Template_CommonSexNPC_MxF", false, 1)]
		public static void CreateHF_Template_CommonSexNPC_MxF() {
			HFramework.EditorUI.GenerateSexScriptTemplate.CreateFromTemplate("Packages/com.yotan-dev.hframework/Runtime/SexScriptTemplates/HF.Template.CommonSexNPC.MxF.asset");
		}
	}
}
#endif
