#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using HFramework.SexScripts;
using System.Collections.Generic;
using System.IO;

namespace HFramework.EditorUI
{
	public static class GenerateSexScriptTemplate
	{
		[MenuItem("Assets/Generate Sex Script Template Menu", validate = true)]
		private static bool GenerateSexScriptTemplateValidation() {
			// Check if the selected asset is a SexScript
			var selectedObjects = Selection.assetGUIDs;
			if (selectedObjects.Length == 0) {
				return false;
			}

			foreach (var selectedObject in selectedObjects) {
				var path = AssetDatabase.GUIDToAssetPath(selectedObject);
				var asset = AssetDatabase.LoadAssetAtPath<SexScript>(path);

				if (asset == null) {
					return false;
				}
			}

			return true;
		}

		[MenuItem("Assets/Generate Sex Script Template Menu")]
		private static void GenerateSexScriptTemplateAction() {
			var selectedObjects = Selection.assetGUIDs;
			if (selectedObjects.Length == 0) {
				return;
			}

			string clickedPath = Path.GetDirectoryName(AssetDatabase.GUIDToAssetPath(Selection.assetGUIDs[0]));

			List<(string path, SexScript asset)> assets = new();
			foreach (var selectedObject in selectedObjects) {
				var path = AssetDatabase.GUIDToAssetPath(selectedObject);
				var asset = AssetDatabase.LoadAssetAtPath<SexScript>(path);

				if (asset != null) {
					assets.Add((path, asset));
				}
			}

			GenerateTemplateClass(clickedPath, assets);
		}

		public static void CreateFromTemplate(string templatePath) {
			if (Selection.assetGUIDs.Length == 0) {
				return;
			}

			try {
				// Gets the path of the folder you right-clicked in or on
				string path = AssetDatabase.GUIDToAssetPath(Selection.assetGUIDs[0]);
				string uniquePath = AssetDatabase.GenerateUniqueAssetPath(path + "/SampleTemplate.asset");

				Debug.Log($"Creating from template {templatePath} to {uniquePath}");
				AssetDatabase.CopyAsset(templatePath, uniquePath);
				AssetDatabase.SaveAssets();
				Debug.Log($"{uniquePath} created from template");
			} catch (System.Exception e) {
				Debug.LogError($"Failed to create from template: {e.Message}");
			}
		}

		private static void GenerateTemplateClass(string clickedPath, List<(string path, SexScript asset)> assets) {
			var templateContent = GenerateTemplateContent(assets);

			// We must be in an editor folder or subfolder, otherwise Unity will break.
			if (!clickedPath.Contains("/Editor/", System.StringComparison.OrdinalIgnoreCase)) {
				clickedPath += "/Editor";
			}

			Directory.CreateDirectory(clickedPath);

			var outputPath = AssetDatabase.GenerateUniqueAssetPath($"{clickedPath}/HFrameworkTemplates_Menus.cs");
			File.WriteAllText(outputPath, templateContent);

			AssetDatabase.Refresh();

			Debug.Log($"Generated template class: {outputPath}");
		}

		private static string SanitizeClassName(string name) {
			// Remove invalid characters and ensure it starts with a letter
			var sanitized = System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9]", "_");
			if (string.IsNullOrEmpty(sanitized) || char.IsDigit(sanitized[0])) {
				sanitized = "Template_" + sanitized;
			}

			return sanitized;
		}

		private static string GenerateTemplateContent(List<(string path, SexScript asset)> assets) {
			var sb = new System.Text.StringBuilder();

			sb.AppendLine("/* Auto-generated by HFramework. This must stay in an Editor folder */");
			sb.AppendLine("using UnityEngine;");
			sb.AppendLine("using UnityEditor;");
			sb.AppendLine("using HFramework.EditorUI;");
			sb.AppendLine("using HFramework.SexScripts;");
			sb.AppendLine("using HFramework.ScriptNodes;");
			sb.AppendLine();
			sb.AppendLine("namespace HFrameworkTemplates /* You can customize if you want */");
			sb.AppendLine("{");
			sb.AppendLine($"	public partial class HFrameworkTemplates_Menus");
			sb.AppendLine("	{");

			foreach (var asset in assets) {
				var scriptName = SanitizeClassName(asset.asset.name);
				sb.AppendLine($"		[MenuItem(\"Assets/Create/HFramework/{scriptName}\", false, 1)]");
				sb.AppendLine($"		public static void Create{scriptName}() {{");
				sb.AppendLine($"			HFramework.EditorUI.GenerateSexScriptTemplate.CreateFromTemplate(\"{asset.path}\");");
				sb.AppendLine($"		}}");
			}
			sb.AppendLine("	}");
			sb.AppendLine("}");

			return sb.ToString();
		}
	}
}
#endif
